import { Transaction } from './types'

export const mockTransactions: Transaction[] = [
  // March 20, 2024
  {
    id: '1',
    transaction_type: 'credit',
    amount: 2000.00,
    merchant: 'IBM',
    date: new Date('2024-03-20'),
    account_id: '1',
    category: 'paychecks',
    notes: 'Monthly salary',
  },
  {
    id: '2',
    transaction_type: 'credit',
    amount: 2200.00,
    merchant: 'University of Illinois',
    date: new Date('2024-03-20'),
    account_id: '1',
    category: 'paychecks',
    notes: 'Teaching assistant salary',
  },
  // March 18, 2024
  {
    id: '3',
    transaction_type: 'debit',
    amount: 90.91,
    merchant: 'State Farm',
    date: new Date('2024-03-18'),
    account_id: '2',
    category: 'auto-payment',
    notes: 'Car insurance',
  },
  {
    id: '4',
    transaction_type: 'debit',
    amount: 110.54,
    merchant: 'State Farm',
    date: new Date('2024-03-18'),
    account_id: '2',
    category: 'auto-payment',
    notes: 'Home insurance',
  },
  {
    id: '5',
    transaction_type: 'debit',
    amount: 500.23,
    merchant: 'Student Loan Payment',
    date: new Date('2024-03-18'),
    account_id: '1',
    category: 'auto-payment',
    notes: 'Monthly loan payment',
  },
  {
    id: '6',
    transaction_type: 'debit',
    amount: 320.47,
    merchant: 'HOA Monthly Dues',
    date: new Date('2024-03-18'),
    account_id: '1',
    category: 'mortgage',
    notes: 'HOA fee',
  },
  {
    id: '7',
    transaction_type: 'debit',
    amount: 39.99,
    merchant: 'Peloton',
    date: new Date('2024-03-18'),
    account_id: '2',
    category: 'other-income',
    notes: 'Monthly subscription',
  },
  {
    id: '8',
    transaction_type: 'debit',
    amount: 115.00,
    merchant: 'Comcast',
    date: new Date('2024-03-18'),
    account_id: '1',
    category: 'internet-cable',
    notes: 'Internet and cable',
  },
  {
    id: '9',
    transaction_type: 'debit',
    amount: 140.00,
    merchant: 'Verizon',
    date: new Date('2024-03-18'),
    account_id: '1',
    category: 'phone',
    notes: 'Phone bill',
  },
  {
    id: '10',
    transaction_type: 'debit',
    amount: 1385.00,
    merchant: 'Wells Fargo',
    date: new Date('2024-03-18'),
    account_id: '1',
    category: 'mortgage',
    notes: 'Mortgage payment',
  },
  // March 18, 2024 continued
  {
    id: '11',
    transaction_type: 'debit',
    amount: 150.00,
    merchant: 'Pampered Pet Care',
    date: new Date('2024-03-18'),
    account_id: '2',
    category: 'other-income',
    notes: 'Pet grooming',
  },
  {
    id: '12',
    transaction_type: 'debit',
    amount: 88.00,
    merchant: 'Home Depot',
    date: new Date('2024-03-18'),
    account_id: '2',
    category: 'home-improvement',
    notes: 'Garden supplies',
  },
  {
    id: '13',
    transaction_type: 'debit',
    amount: 120.00,
    merchant: 'Gardening Services',
    date: new Date('2024-03-18'),
    account_id: '1',
    category: 'home-improvement',
    notes: 'Lawn care',
  },
  {
    id: '14',
    transaction_type: 'debit',
    amount: 5.00,
    merchant: 'Starbucks',
    date: new Date('2024-03-18'),
    account_id: '2',
    category: 'coffee-shops',
    notes: 'Morning coffee',
  },
  {
    id: '15',
    transaction_type: 'debit',
    amount: 12.12,
    merchant: 'Chipotle',
    date: new Date('2024-03-18'),
    account_id: '2',
    category: 'restaurants',
    notes: 'Lunch',
  },
  // March 17, 2024
  {
    id: '16',
    transaction_type: 'debit',
    amount: 43.00,
    merchant: 'Exxon',
    date: new Date('2024-03-17'),
    account_id: '2',
    category: 'gas',
    notes: 'Gas fill up',
  },
  {
    id: '17',
    transaction_type: 'debit',
    amount: 108.00,
    merchant: 'ComEd',
    date: new Date('2024-03-17'),
    account_id: '1',
    category: 'gas-electric',
    notes: 'Electric bill',
  },
  {
    id: '18',
    transaction_type: 'debit',
    amount: 5.00,
    merchant: 'Uber',
    date: new Date('2024-03-17'),
    account_id: '2',
    category: 'taxi-rideshares',
    notes: 'Ride home',
  },
  // March 16, 2024
  {
    id: '19',
    transaction_type: 'debit',
    amount: 156.78,
    merchant: 'Walmart',
    date: new Date('2024-03-16'),
    account_id: '2',
    category: 'groceries',
    notes: 'Weekly groceries',
  },
  {
    id: '20',
    transaction_type: 'debit',
    amount: 45.32,
    merchant: 'Target',
    date: new Date('2024-03-16'),
    account_id: '2',
    category: 'groceries',
    notes: 'Household items',
  },
  // March 15, 2024
  {
    id: '21',
    transaction_type: 'debit',
    amount: 89.99,
    merchant: 'Amazon',
    date: new Date('2024-03-15'),
    account_id: '2',
    category: 'other-income',
    notes: 'Online shopping',
  },
  {
    id: '22',
    transaction_type: 'debit',
    amount: 25.50,
    merchant: 'McDonald\'s',
    date: new Date('2024-03-15'),
    account_id: '2',
    category: 'restaurants',
    notes: 'Family dinner',
  },
  // March 10, 2024
  {
    id: '23',
    transaction_type: 'debit',
    amount: 125.00,
    merchant: 'Costco',
    date: new Date('2024-03-10'),
    account_id: '2',
    category: 'groceries',
    notes: 'Bulk shopping',
  },
  {
    id: '24',
    transaction_type: 'debit',
    amount: 15.99,
    merchant: 'Netflix',
    date: new Date('2024-03-10'),
    account_id: '1',
    category: 'other-income',
    notes: 'Monthly subscription',
  },
  {
    id: '25',
    transaction_type: 'debit',
    amount: 9.99,
    merchant: 'Spotify',
    date: new Date('2024-03-10'),
    account_id: '1',
    category: 'other-income',
    notes: 'Monthly subscription',
  },
  // March 5, 2024
  {
    id: '26',
    transaction_type: 'debit',
    amount: 67.89,
    merchant: 'Apple',
    date: new Date('2024-03-05'),
    account_id: '2',
    category: 'other-income',
    notes: 'App Store purchases',
  },
  {
    id: '27',
    transaction_type: 'debit',
    amount: 42.50,
    merchant: 'Starbucks',
    date: new Date('2024-03-05'),
    account_id: '2',
    category: 'coffee-shops',
    notes: 'Weekly coffee runs',
  },
  // February 28, 2024
  {
    id: '28',
    transaction_type: 'debit',
    amount: 234.56,
    merchant: 'Whole Foods',
    date: new Date('2024-02-28'),
    account_id: '2',
    category: 'groceries',
    notes: 'Organic groceries',
  },
  {
    id: '29',
    transaction_type: 'credit',
    amount: 500.00,
    merchant: 'Tax Refund',
    date: new Date('2024-02-28'),
    account_id: '1',
    category: 'other-income',
    notes: 'Federal tax refund',
  },
  // February 20, 2024
  {
    id: '30',
    transaction_type: 'credit',
    amount: 2000.00,
    merchant: 'IBM',
    date: new Date('2024-02-20'),
    account_id: '1',
    category: 'paychecks',
    notes: 'Monthly salary',
  },
]
